param()
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$RootBase=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\VideoProduction'
$RunRoot=Join-Path $RootBase ('AUTO_QA_'+(Get-Date -Format 'yyyyMMdd-HHmmss'))
$Out=Join-Path $RunRoot 'out'
New-Item -ItemType Directory -Force -Path $Out|Out-Null
$Log=Join-Path $RunRoot 'auto-qa.log'
function L([string]$M){Add-Content -LiteralPath $Log -Value ('['+(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')+'] '+$M) -Encoding UTF8}
function U([string]$B){[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($B))}
function Q([string]$S){if($S -match '[\s"]'){return '"'+($S -replace '"','\"')+'"'};return $S}
function KillTree([int]$ProcessId){try{& taskkill.exe /PID $ProcessId /T /F 2>$null|Out-Null}catch{try{Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue}catch{}}}
function RunP([string]$Exe,[string[]]$Args,[int]$Timeout,[string]$Cwd,[string]$LogPath){$Psi=New-Object Diagnostics.ProcessStartInfo;$Psi.FileName=$Exe;$Psi.WorkingDirectory=$Cwd;$Psi.UseShellExecute=$false;$Psi.CreateNoWindow=$true;$Psi.RedirectStandardOutput=$true;$Psi.RedirectStandardError=$true;$Psi.Arguments=(@($Args)|ForEach-Object{Q ([string]$_)})-join ' ';$P=New-Object Diagnostics.Process;$P.StartInfo=$Psi;[void]$P.Start();$OT=$P.StandardOutput.ReadToEndAsync();$ET=$P.StandardError.ReadToEndAsync();if(-not $P.WaitForExit($Timeout*1000)){KillTree ([int]$P.Id);try{[void]$P.WaitForExit(3000)}catch{};$O='';$E='';try{$O=$OT.Result}catch{};try{$E=$ET.Result}catch{};($O+"`r`n"+$E)|Set-Content -LiteralPath $LogPath -Encoding UTF8;return [ordered]@{ok=$false;code=124;timedOut=$true;stdout=$O;stderr=$E}};$P.WaitForExit();$O=$OT.Result;$E=$ET.Result;($O+"`r`n"+$E)|Set-Content -LiteralPath $LogPath -Encoding UTF8;return [ordered]@{ok=($P.ExitCode -eq 0);code=$P.ExitCode;timedOut=$false;stdout=$O;stderr=$E}}
function FindFfmpeg{$F=Get-Command ffmpeg.exe -ErrorAction SilentlyContinue;$P=Get-Command ffprobe.exe -ErrorAction SilentlyContinue;if($F -and $P){return [pscustomobject]@{ff=$F.Source;fp=$P.Source}};$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\Tools\ffmpeg';$FF=Get-ChildItem -LiteralPath $Base -Recurse -Filter ffmpeg.exe -File -ErrorAction SilentlyContinue|Select-Object -First 1;$FP=Get-ChildItem -LiteralPath $Base -Recurse -Filter ffprobe.exe -File -ErrorAction SilentlyContinue|Select-Object -First 1;if($FF -and $FP){return [pscustomobject]@{ff=$FF.FullName;fp=$FP.FullName}};throw 'FFMPEG_NOT_FOUND'}
function FindCentral{$Target=U 'MDBf7KSR7JWZ7JeQ7J207KCE7Yq4';foreach($D in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$R=[string]$D.Root;if(-not $R){continue};foreach($C in @((Join-Path $R $Target),(Join-Path $R ('My Drive\'+$Target)),(Join-Path $R ('Google Drive\'+$Target)))){if(Test-Path -LiteralPath $C){return $C}}};foreach($C in @((Join-Path $env:USERPROFILE ('My Drive\'+$Target)),(Join-Path $env:USERPROFILE ('Google Drive\'+$Target)))){if(Test-Path -LiteralPath $C){return $C}};return ''}
function LatestVideo{$Dirs=Get-ChildItem -LiteralPath $RootBase -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name -match '^V(11|10|9)_'}|Sort-Object LastWriteTime -Descending;foreach($D in $Dirs){$V=Join-Path $D.FullName 'out\2026-08-24_AGENT_DASHBOARD_PROMO_CONTENTOS_E2E_V1.mp4';if(Test-Path -LiteralPath $V){try{if((Get-Item -LiteralPath $V).Length -gt 100000){return $V}}catch{}}};return ''}
$Tools=FindFfmpeg;$env:PATH=(Split-Path $Tools.ff -Parent)+';'+$env:PATH
$Video=LatestVideo
if(-not $Video){throw 'NO_COMPLETED_V11_MP4_FOUND'}
L ('Reuse existing MP4: '+$Video)
$ManifestJson=U 'eyJtYW5pZmVzdFZlcnNpb24iOiJWSURFT19QUk9EVUNUSU9OX01BTklGRVNUX1YxXzIwMjYwODI0IiwiYXNzZXRJZCI6IkFHRU5UX0RBU0hCT0FSRF9QUk9NT19DT05URU5UT1NfRTJFXzIwMjYwODI0IiwidGVtcGxhdGVJZCI6IkFHRU5UX0RBU0hCT0FSRF9QUk9NT19FMkVfVjEiLCJjb21wbGV4aXR5Q2xhc3MiOiJERU1PIiwiY2FudmFzIjp7ImFzcGVjdCI6Ijk6MTYiLCJ3aWR0aCI6MTA4MCwiaGVpZ2h0IjoxOTIwLCJmcHMiOjMwfSwic2hvdHMiOlt7InNob3RJZCI6IlNIT1RfMDEiLCJibG9ja0lkIjoiSE9PSyIsInN0YXJ0U2VjIjowLCJlbmRTZWMiOjMsInNjcmVlblByb29mUmVxdWlyZWQiOmZhbHNlLCJjYXB0aW9uVGV4dCI6Iuy9mO2FkOy4oCBPUyDsi6TsoJwg7J6R64+ZIO2ZlOuptCJ9LHsic2hvdElkIjoiU0hPVF8wMiIsImJsb2NrSWQiOiJQUk9PRiIsInN0YXJ0U2VjIjozLCJlbmRTZWMiOjcsInNjcmVlblByb29mUmVxdWlyZWQiOnRydWUsImNhcHRpb25UZXh0Ijoi7Iuk7KCcIFByb2R1Y3Rpb24g7ZmU66m0IO2ZleyduCJ9LHsic2hvdElkIjoiU0hPVF8wMyIsImJsb2NrSWQiOiJXT1JLRkxPVyIsInN0YXJ0U2VjIjo3LCJlbmRTZWMiOjEyLCJzY3JlZW5Qcm9vZlJlcXVpcmVkIjp0cnVlLCJjYXB0aW9uVGV4dCI6IuyeheugpSDihpIg67aE7ISdIOKGkiDqsrDqs7wg7Z2Q66aEIn0seyJzaG90SWQiOiJTSE9UXzA0IiwiYmxvY2tJZCI6IlZBTFVFIiwic3RhcnRTZWMiOjEyLCJlbmRTZWMiOjE3LCJzY3JlZW5Qcm9vZlJlcXVpcmVkIjp0cnVlLCJjYXB0aW9uVGV4dCI6IuuwmOuztSDsnpHsl4Ug6rCQ7IaMIMK3IOqysOqzvCDthrXtlakg6rSA66asIn0seyJzaG90SWQiOiJTSE9UXzA1IiwiYmxvY2tJZCI6IkNUQSIsInN0YXJ0U2VjIjoxNywiZW5kU2VjIjoyMCwic2NyZWVuUHJvb2ZSZXF1aXJlZCI6ZmFsc2UsImNhcHRpb25UZXh0Ijoi7Iuk7KCcIOuPmeyekeydhCDtmZXsnbjtlbQg67O07IS47JqUIn1dfQ=='
try{[void]($ManifestJson|ConvertFrom-Json)}catch{throw ('MANIFEST_DECODE_FAILED '+$_.Exception.Message)}
$ManifestPath=Join-Path $RunRoot 'production-manifest.json';[IO.File]::WriteAllText($ManifestPath,$ManifestJson,(New-Object Text.UTF8Encoding($true)))
$Qa=Join-Path $RunRoot 'Run-VideoFrameQA.ps1';Invoke-WebRequest -UseBasicParsing -Uri 'https://raw.githubusercontent.com/8friend8ship-cloud/animation/codex/video-promo-agent-workflow-20260823/tools/Run-VideoFrameQA.ps1' -OutFile $Qa -TimeoutSec 60;$Qt=[IO.File]::ReadAllText($Qa,[Text.Encoding]::UTF8);[IO.File]::WriteAllText($Qa,$Qt,(New-Object Text.UTF8Encoding($true)))
$Wrapper=Join-Path $RunRoot 'qa-wrapper.ps1';$Wt=@'
param([string]$Qa,[string]$Video,[string]$Manifest,[int]$Pass,[string]$Out)
$ErrorActionPreference='Continue'
$J=[IO.File]::ReadAllText($Manifest,[Text.Encoding]::UTF8)
& $Qa -VideoPath $Video -ManifestJson $J -PassNumber $Pass -OutputDir $Out
exit $LASTEXITCODE
'@;[IO.File]::WriteAllText($Wrapper,$Wt,(New-Object Text.UTF8Encoding($true)))
$Results=@()
foreach($Pass in @(1,2)){$Dir=Join-Path $Out ('QA_PASS_'+$Pass);New-Item -ItemType Directory -Force -Path $Dir|Out-Null;$R=RunP 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$Wrapper,'-Qa',$Qa,'-Video',$Video,'-Manifest',$ManifestPath,'-Pass',[string]$Pass,'-Out',$Dir) 180 $RunRoot (Join-Path $Dir 'qa-console.log');$SummaryPath=Join-Path $Dir '00_FRAME_QA_SUMMARY.json';if(-not(Test-Path -LiteralPath $SummaryPath)){throw ('QA_'+$Pass+'_NO_SUMMARY exit='+$R.code)};$S=Get-Content -LiteralPath $SummaryPath -Raw -Encoding UTF8|ConvertFrom-Json;if(-not $S.ok){throw ('QA_'+$Pass+'_FAIL '+$S.status+' failedShots='+(@($S.failedShotIds)-join ','))};$Results+=$S;L ('QA'+$Pass+' PASS '+$S.status)}
$Central=FindCentral;$Drive=''
if($Central){$Drive=Join-Path $Central 'Video_Production\2026\08\AGENT_DASHBOARD_PROMO_FIRST_MP4_20260824';New-Item -ItemType Directory -Force -Path $Drive|Out-Null;Copy-Item -LiteralPath $Video -Destination (Join-Path $Drive ([IO.Path]::GetFileName($Video))) -Force;Copy-Item -LiteralPath $ManifestPath -Destination (Join-Path $Drive 'production-manifest.json') -Force;foreach($Name in @('QA_PASS_1','QA_PASS_2')){Copy-Item -LiteralPath (Join-Path $Out $Name) -Destination $Drive -Recurse -Force}}
$Result=[ordered]@{ok=$true;status='MP4_TECHNICAL_QA_X2_PASS_VISUAL_REVIEW_PENDING';video=$Video;driveOutput=$Drive;qa1=[string]$Results[0].status;qa2=[string]$Results[1].status;animationE2E='DEFERRED_SEPARATE_GATE';runRoot=$RunRoot;completedAt=(Get-Date).ToString('o')};$ResultPath=Join-Path $Out 'VIDEO_AUTO_RECOVERY_RESULT.json';$Result|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $ResultPath -Encoding UTF8;if($Drive){$Result|ConvertTo-Json -Depth 20|Set-Content -LiteralPath (Join-Path $Drive 'VIDEO_AUTO_RECOVERY_RESULT.json') -Encoding UTF8};$Result|ConvertTo-Json -Compress -Depth 20
exit 0
